---
title: "Mainauenlauf - Statistik"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    source_code: https://github.com/JohannesFriedrich/Mainauenlauf
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rvest)
library(tidyverse)
library(httr)
library(plotly)
library(DT)
load("../Mainauenlauf_data.Rds")
```

```{r}
get_surnames <- function(data){
  
  names <- unlist(lapply(data, function(name){
  
  temp <- strsplit(name, " ")
  
  temp[[1]][1]
  }))
  
  return(names)
  
}
```


Teilnehmer-Statistiken
=======================================================================

Row
-----------------------------------------------------------------------

### Gesamtteilnehmer {data-width=300} 

```{r}
g <- all_data %>% 
  group_by(Jahr, Geschlecht) %>% 
  tally() %>% 

ggplot(aes(Jahr, y = n)) + 
  geom_bar(aes(fill = Geschlecht), stat = "identity", position = "stack") +
  #geom_point(aes(color = Geschlecht), position = position_dodge2(width = 1)) +
  #geom_line(aes(group = Geschlecht), position = position_dodge2(width = 1)) +
  theme(legend.position = "bottom") +
  labs(x = "Jahr", y = "Teilnehmer")

# g
plotly::ggplotly(g) %>% 
  layout(legend = list(orientation = "h", x = 0.4, y = -0.2))

```

### Vereine


```{r}
g <- all_data %>% 
  group_by(Jahr, Verein) %>% 
  tally() %>% 
  filter(Verein != "",
         Verein != "-") %>% 
  slice_max(n, n = 3) %>% 
  
  ggplot() + 
  geom_bar(aes(Jahr, y = n, fill = Verein), stat = "identity", position = "dodge2") +
  theme(legend.position = "bottom") +
  labs(x = "Jahr", y = "Teilnehmer")

plotly::ggplotly(g)
```



Row
----------------

### Altersklassen {data-width=700}

```{r}
g <- all_data %>% 
  group_by(Jahr, Geschlecht, AK) %>% 
  tally() %>% 
  #slice_max(n, n = 3)

ggplot() + 
  geom_bar(aes(Jahr, y = n, fill = AK), stat = "identity", position = "dodge2") +
  theme(legend.position = "none") +
  labs(x = "Jahr", y = "Teilnehmer") +
  facet_wrap(~Geschlecht)

plotly::ggplotly(g)
```

Row
--------

### Vornamen

```{r}
g <- all_data %>% 
  mutate(Vorname = get_surnames(Name)) %>% 
  group_by(Geschlecht, Vorname) %>% 
  tally() %>% 
  slice_max(n, n= 5) %>% 
  mutate(Vorname =  factor(Vorname, levels=Vorname)) %>% 
  
  ggplot() + 
  geom_bar(aes(Geschlecht, y = n, fill = Vorname), stat = "identity", position = "dodge2") +
  theme(legend.position = "bottom") +
  labs(x = "Geschlecht", y = "Teilnehmer")

plotly::ggplotly(g)
```

### Dauerteilnehmer (mindestens 4 Teilnahmen)

```{r}
all_data %>% 
  group_by(Geschlecht, Name) %>% 
  summarise(Teilnahmen = n()) %>% 
  ungroup() %>% 
  filter(Teilnahmen >= 4) %>% 
  DT::datatable()
```

Zeit-Statistiken
=======================================================================

Row
---------

### Zeiten nach Jahr {data-width=600}

```{r Zeiten_Boxplot}

all_data %>% 
plot_ly(x = ~Jahr, y = ~Zeit2, color = ~Geschlecht) %>% 
  add_boxplot() %>% 
  layout(xaxis = list(title = "Jahr"), yaxis = list(title = "Zeit"))
```

### Zeit vs. Startnummer

```{r}
g <- all_data %>% 
  group_by(Geschlecht) %>% 
  
  ggplot(aes(Zeit, Startnummer, color = Jahr, text = paste0("Name: ",Name))) +
  geom_point(size = 0.8, alpha = 0.6) +
  scale_x_time() +
  facet_grid(Jahr~Geschlecht) +
  theme(legend.position = "none") +
  labs(x="Zeit", y = "Platzierung")

plotly::ggplotly(g)
```

Row
--------

### Zeit vs. Platzierungen

```{r}
g <- all_data %>% 
  group_by(Geschlecht) %>% 
  
  ggplot(aes(Zeit, Platz, color = Jahr, text = paste0("Name: ",Name))) +
  geom_point(size = 0.8, alpha = 0.6) +
  scale_x_time() +
  facet_wrap(~Geschlecht) +
  theme(legend.position = "none") +
  labs(x="Zeit", y = "Platzierung")

plotly::ggplotly(g)
  
```

Row
--------

### Zeiten nach Altersklassen

```{r}
g <- all_data %>% 
  mutate(Zeit_seconds = lubridate::seconds(Zeit)) %>% 
  group_by(Jahr, Geschlecht, AK) %>% 
  summarise(avg_time = mean(Zeit_seconds),
            n = n()) %>% 
  mutate(Zeit =  lubridate::seconds_to_period(avg_time)) %>% 
  
  ggplot(aes(Jahr, Zeit, color = AK)) +
  geom_point() +
  scale_y_time() +
  facet_wrap(~Geschlecht) +
  labs(x="Jahr", y = "Zeit")

plotly::ggplotly(g)
```

### Zeitunterschiede bei mind. 2 Teilnahmen

```{r}
names <- all_data %>% 
  group_by(Geschlecht, Name) %>% 
  summarise(Teilnahmen = n()) %>% 
  ungroup() %>% 
  filter(Teilnahmen >= 2) %>% 
  select(Geschlecht, Name, Teilnahmen) %>% 
  arrange(-desc(Name))

diff <- all_data %>% 
  filter(Name %in% names$Name) %>% 
  arrange(-desc(Name)) %>% 
  group_by(Name) %>% 
  mutate(Zeit_seconds = lubridate::seconds(Zeit)) %>% 
  summarise(min_time = min(Zeit_seconds),
            max_time = max(Zeit_seconds)) %>% 
    mutate(Geschlecht = names$Geschlecht) %>% 

  mutate(`Differenz` =  lubridate::seconds_to_period(max_time - min_time)) %>% 
  select(-c(min_time, max_time)) %>% 
  mutate(Teilnahmen = names$Teilnahmen) %>% 
  arrange(desc(`Teilnahmen`)) %>% 
  mutate(Differenz = paste0(`Differenz`@minute, ":", Differenz@.Data))

diff %>%  
  DT::datatable()
```


Alle Daten
=======================================================================

```{r}
all_data %>% 
  select(-c(Zeit)) %>%
  mutate(Zeit = Zeit2) %>% 
  select(-c(Zeit2)) %>% 
  DT::datatable()
```

